### ISSUE TITLE
Color contrast in the settings lateral panel

### ISSUE THREAD

**Issue by JeanValjean30** [vinceliuice/Magnetic-gtk-theme#14]
Hi, Vince.

The lateral panel in "settings" doesn't respect the color contrast.

Thanks

![Screenshot from 2024-11-30 23-41-41](https://github.com/user-attachments/assets/375ec7b1-871c-472a-9b33-238bbc11dba8)

**Comment by vinceliuice** [comment]
What's your desktop version ?

**Comment by JeanValjean30** [comment]
> What's your desktop version ?

Hi. Thanks for the replay. I'm on Debian 12 with Gnome 43.9.

**Comment by JeanValjean30** [comment]
Same with clapgrep.

![Screenshot from 2024-12-08 16-25-34](https://github.com/user-attachments/assets/2d2a4c0f-4acd-4845-8912-9a10beae0fec)
