### ISSUE TITLE
text not readable in statusbar in gnome files

### ISSUE THREAD

**Issue by paolocalosso** [vinceliuice/Magnetic-gtk-theme#2]
Hello, i'm trying your new and wonderful theme. I installed dark using both tweaks black and gruvbox but now i cannot read text in statusbar in gnome Files when select an object
![Screenshot from 2023-10-13 13-34-53](https://github.com/vinceliuice/Magnetic-gtk-theme/assets/5927377/4b5d54af-5a74-4530-838b-cf3ff983f514)

many thanks for your work!

**Comment by vinceliuice** [comment]
What's your nautilus version ?

**Comment by paolocalosso** [comment]
gnome 44, Ubuntu 23.04

**Comment by vinceliuice** [comment]
OK, I get it, I'll test it on 44 version

**Comment by vinceliuice** [comment]
![Screenshot from 2023-10-14 00-30-18](https://github.com/vinceliuice/Magnetic-gtk-theme/assets/7604295/88cb24f1-70b7-4a12-8083-76deb8d7c218)

**Comment by vinceliuice** [comment]
You need to install this theme with `-l` option to force libadwaita app use this theme

**Comment by paolocalosso** [comment]
I think I installed with -l option and I also edited .profile file to force the theme. later I'm going to double check and try again.

**Comment by paolocalosso** [comment]
I think I installed with -l option and I also edited .profile file to force the theme. later I'm going to double check and try again.

**Comment by vinceliuice** [comment]
Edited .profile to use this theme will have lower priority than theme code build in Nautilus itself, just use `-l` option it use ~/.config/gtk-4.0/gtk.css file this one have higher priority

**Comment by paolocalosso** [comment]
ok you were right, editing .profile file was causing the issue! 
thank you very much!
